### ISSUE TITLE
Toml don't parse .gitconfig

### ISSUE THREAD

**Issue by mackwic** [ocaml-toml/To.ml#10]
Related issue: #8

To.ml parse error on a .gitconfig. It seems to be the tab in the begin of the line.

Standard test case:

``` ocaml
# #require "toml";;
# let _ = Toml.Parser.from_filename "/Users/thomas/.gitconfig" in ();;
Exception:
Toml.Parser.Error
 ("Error in /Users/thomas/.gitconfig at line 2 at column 14 (position 21)",
  {Toml.Parser.source = "/Users/thomas/.gitconfig"; line = 2; column = 14;
   position = 21}).
```

Funny thing, the github parser is broken in the same way.

``` toml
# my ~/.gitconfig
[user]
    name = Thomas Wickham
    email = thomas@wickham.epimeros.org
[pull]
    default = simple
[push]
    default = simple
[github]
    user = mackwic
[color]
    ui = auto
[filter "media"]
    required = true
    clean = git media clean %f
    smudge = git media smudge %f
[core]
    excludesfile = /Users/thomas/.gitignore_global
[difftool "sourcetree"]
    cmd = opendiff \"$LOCAL\" \"$REMOTE\"
    path = 
[mergetool "sourcetree"]
    cmd = /Applications/SourceTree.app/Contents/Resources/opendiff-w.sh \"$LOCAL\" \"$REMOTE\" -ancestor \"$BASE\" -merge \"$MERGED\"
    trustExitCode = true
[branch]
    autosetupmerge = always
```

I work on this this evening, should be solved by tomorrow.
